import { beforeAll, afterAll, it, expect } from 'vitest';
import { localIntegration } from './local-integration.js';
import { performStage } from '../src/runner.js';
let app: Awaited<ReturnType<typeof localIntegration>>;
beforeAll(async()=>{app=await localIntegration();},30000);
afterAll(async()=>{await app?.cleanup();});
it('authenticates real JWTs, refuses participants and protects database tables',async()=>{
 expect((await app.request('/runs')).status).toBe(422);
 expect((await app.request('/runs','GET',undefined,null)).status).toBe(401);
 expect((await app.request('/runs','GET',undefined,'invalid')).status).toBe(401);
 expect((await app.request('/runs','GET',undefined,app.participant.token)).status).toBe(403);
 for(const table of ['brief_runs','brief_run_steps','brief_budget','brief_call_receipts']) expect((await app.participant.client.from(table).select('*')).error).not.toBeNull();
 expect((await app.request('/runs','POST',{sessionId:app.source.id,requestId:crypto.randomUUID(),source_context:{injected:true}})).status).toBe(422);
 expect((await app.request('/runs','POST',{text:'x'.repeat(5000)})).status).toBe(413);
});
it('runs stored OpenAI output through persistence, review/export and rejects stale/deleted evidence',async()=>{
 const id=crypto.randomUUID(), body={sessionId:app.source.id,requestId:id};
 const starts=await Promise.all([app.request('/runs','POST',body),app.request('/runs','POST',body)]);
 expect(starts.map(r=>r.status)).toEqual([202,202]);
 await app.jobs.get(id);
 expect(app.jobs.size).toBe(1); expect(app.replayCalls).toBeGreaterThanOrEqual(5);
 const detail=await (await app.request(`/runs/${id}`)).json() as any;
 expect(detail.run.status).toBe('waiting_admin_review'); expect(detail.steps.length).toBe(app.replayCalls);
 expect((await app.request(`/runs/${id}/export`,'POST',{format:'json'})).status).toBe(409);
 const noProvider=async()=>{throw new Error('Must not call provider on completed step');};
 await performStage(app.store,noProvider,id,'audit');
 expect((await app.request(`/runs/${id}/review`,'POST',{briefHash:'b'.repeat(64),decision:'approve'})).status).toBe(409);
 const review={briefHash:detail.run.brief_hash,decision:'approve'};
 expect((await app.request(`/runs/${id}/review`,'POST',review)).status).toBe(200);
 expect((await app.request(`/runs/${id}/review`,'POST',review)).status).toBe(200);
 expect((await app.request(`/runs/${id}/review`,'POST',{...review,decision:'reject'})).status).toBe(409);
 const exported=await (await app.request(`/runs/${id}/export`,'POST',{format:'json'})).json() as any;
 expect(JSON.parse(exported.content).review.reviewedBy).toBe(app.admin.email);
 expect(JSON.parse(exported.content).review.status).toBe('exported');
 const changed={...app.source,revision:3};
 expect((await app.db.from('interview_sessions').update({state:changed,revision:3}).eq('id',app.source.id)).error).toBeNull();
 expect((await app.request(`/runs/${id}/export`,'POST',{format:'json'})).status).toBe(409);
 expect((await app.request('/runs','POST',body)).status).toBe(409);
 await app.db.from('interview_sessions').delete().eq('id',app.source.id);
 expect((await app.request(`/runs/${id}`)).status).toBe(404);
 expect((await app.db.from('brief_run_steps').select('*').eq('run_id',id)).data).toEqual([]);
 expect((await app.db.from('brief_call_receipts').select('id')).data!.length).toBeGreaterThanOrEqual(5);
},30000);
